plugin: aws_ec2
aws_profile: default
regions:
  - us-east-1

hostnames:
  - ip-address

# keyed_groups:
#   - key: tags
#     prefix: tag
#   - key: instance_type
#     prefix: instance_type
#   - key: placement.region
#     prefix: aws_region
#   - key: placement.availability_zone
#     prefix: az

groups:
  redhat: "'ansible_redhat' in tags.Name"
  debian: "'ansible_debian' in tags.Name"